version: '3.9' # optional since v1.27.0

networks:
  rento2:
    name: rento2

services:
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rento2_rabbitmq
    restart: unless-stopped
    ports:
      - ${RABBITMQ_PORT}:5672
    networks:
      rento2:

  redis:
    image: redis:6.2.4-alpine
    container_name: rento2_redis
    restart: unless-stopped
    ports:
      - ${REDIS_PORT}:6379
    networks:
      rento2:

  postgres:
    image: postgres:12.1
    container_name: rento2_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /data/postgres
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./_docker/data/postgres:/data/postgres
    networks:
      rento2:
