version: '3.9' # optional since v1.27.0

networks:
  rento2:
    name: rento2

volumes:
  dbdata:
    name: rento2_dbdata

services:
  mysql:
    image: mysql:8.0
    container_name: rento2_mysql
    command: --default-authentication-plugin=mysql_native_password
    env_file: .env
    volumes:
      - dbdata:/var/lib/mysql
    # Best not use for production, this is insecure
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DB_NAME}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    ports:
      - ${MYSQL_PORT}:3306
    networks:
      rento2:
