version: '3.9' # optional since v1.27.0

networks:
  rento2:
    name: rento2

services:
  postgres:
    image: postgres:12.1
    container_name: rento2_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /data/postgres
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./_docker-data/data/postgres:/data/postgres
      - ./_docker-data/pgsql/init.sh:/docker-entrypoint-initdb.d/init.sh
    networks:
      rento2:

  mysql:
    image: mariadb:10
    container_name: rento2_mysql
    command: --default-authentication-plugin=mysql_native_password
    env_file: .env
    volumes:
      - ./_docker-data/data/mysql:/var/lib/mysql
    # danger, shouldn't be used for production
    environment:
      MYSQL_ALLOW_EMPTY_ROOT_PASSWORD: true
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DB_NAME}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    ports:
      - ${MYSQL_PORT}:3306
    networks:
      rento2:
