version: '3.9' # optional since v1.27.0

networks:
  rento2:
    name: rento2

services:
  postgres:
    image: postgres:12.1
    container_name: rento2_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /data/postgres
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./_docker/data/postgres:/data/postgres
    networks:
      rento2:
