name: Deploy development server

on:
  push:
    branches: [ lukentui/github-actions ]

jobs:
  dev-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Node.JS
      uses: actions/setup-node@v3
      with:
        node-version: 16.0.0

    - name: Process backend
      env:
        SECRET_BACKEND: ${{ secrets.CONFIG_BACKEND }}
      working-directory: ./packages/backend
      run: |
        npm ci
        node ./ace build --production
        echo "$ENV_BACKEND" > ./build/.env

    - name: Process frontend
      working-directory: ./packages/frontend
      env:
        SECRET_FRONTEND: ${{ secrets.CONFIG_FRONTEND }}
      run: |
        echo "$ENV_FRONTEND" > ./.env
        npm ci

    - name: Process admin
      working-directory: ./packages/admin
      env:
        SECRET_ADMIN: ${{ secrets.CONFIG_ADMIN }}
      run: |
        echo "$ENV_ADMIN" > ./.env
        npm ci

    - name: Deploy
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DEV_IP }}
        username: ${{ secrets.DEV_USERNAME }}
        password: ${{ secrets.DEV_PASSWORD }}
        port: ${{ secrets.DEV_PORT }}
        target: /var/www/rento/
        source: "."
        rm: true

    - name: Backend apply changes
      uses: appleboy/ssh-action@master
      env:
        SECRET_PASSWORD: ${{ secrets.DEV_PASSWORD }}
      with:
        host: ${{ secrets.DEV_IP }}
        username: ${{ secrets.DEV_USERNAME }}
        password: ${{ secrets.DEV_PASSWORD }}
        port: ${{ secrets.DEV_PORT }}

        script: |
          pm2 restart /var/www/rento/ecosystem.config.js
          node /var/www/rento/packages/backend/build/ace migration:run
