name: Check pull request's code quality

on:
  push:
    branches:
      - '**'
      - '!master'
      - '!develop'

jobs:
  lint-backend:
    environment: code-quality
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Node.JS
      uses: actions/setup-node@v3
      with:
        node-version: 16.0.0

    - name: Install dependencies
      working-directory: ./packages/backend
      run: npm ci

    - name: Lint
      working-directory: ./packages/backend
      run: npm run lint

  lint-admin:
    environment: code-quality
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Node.JS
      uses: actions/setup-node@v3
      with:
        node-version: 16.0.0

    - name: Install dependencies
      working-directory: ./packages/admin
      run: npm ci

    - name: Lint
      working-directory: ./packages/admin
      run: npm run lint

  lint-frontend:
    environment: code-quality
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Node.JS
      uses: actions/setup-node@v3
      with:
        node-version: 16.0.0

    - name: Install dependencies
      working-directory: ./packages/frontend
      run: npm ci

    - name: Lint
      working-directory: ./packages/frontend
      run: npm run lint


  build-backend:
    environment: code-quality
    runs-on: ubuntu-latest
    needs: lint-backend
    steps:
    - uses: actions/checkout@v2
    - uses: montudor/action-zip@v1

    - name: Install Node.JS
      uses: actions/setup-node@v3
      with:
        node-version: 16.0.0

    - name: Build
      working-directory: ./packages/backend
      env:
        ENV_BACKEND: ${{ secrets.ENV_BACKEND }}
      run: |
        npm ci
        npm install
        npm run build

  build-frontend:
    environment: code-quality
    runs-on: ubuntu-latest
    needs: lint-frontend
    steps:
    - uses: actions/checkout@v2
    - uses: montudor/action-zip@v1

    - name: Install Node.JS
      uses: actions/setup-node@v3
      with:
        node-version: 16.0.0

    - name: Build
      working-directory: ./packages/frontend
      env:
        ENV_FRONTEND: ${{ secrets.ENV_FRONTEND }}
        ZIP_PASSWORD: ${{ secrets.FONTS_ZIP_PASSWORD }}
      run: |
        npm ci
        echo "$ENV_FRONTEND" >> ./.env.local
        unzip -qq -P "$ZIP_PASSWORD"  ./../../.github/fonts.zip -d ./src/app/styles
        npm run build


  build-admin:
    environment: code-quality
    runs-on: ubuntu-latest
    needs: lint-admin
    steps:
    - uses: actions/checkout@v2
    - uses: montudor/action-zip@v1

    - name: Install Node.JS
      uses: actions/setup-node@v3
      with:
        node-version: 16.0.0

    - name: Build
      working-directory: ./packages/admin
      env:
        ENV_ADMIN: ${{ secrets.ENV_ADMIN }}
      run: |
        npm ci
        echo "$ENV_ADMIN" >> ./.env
        npm run build
