name: Check pull request's code quality

on:
  push:
    branches:
      - '**'
      - '!master'
      - '!develop'
      - '!release'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Node.JS
      uses: actions/setup-node@v3
      with:
        node-version: 16.0.0

    - name: Lint backend
      working-directory: ./packages/backend
      run: npm i && ./node_modules/.bin/eslint ./ --ext .ts

    - name: Lint frontend
      working-directory: ./packages/frontend
      run: npm i && eslint ./ --ext .tsx,.ts,.js,.jsx

    - name: Lint admin
      working-directory: ./packages/admin
      run: npm ci && eslint ./ --ext .tsx,.ts,.js,.jsx

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: montudor/action-zip@v1

    - name: Install Node.JS
      uses: actions/setup-node@v3
      with:
        node-version: 16.0.0

    - name: Process backend
      env:
        ENV_BACKEND: ${{ secrets.ENV_BACKEND }}
      working-directory: ./packages/backend
      run: |
        npm ci
        node ./ace build --production

    - name: Process frontend
      working-directory: ./packages/frontend
      env:
        ENV_FRONTEND: ${{ secrets.ENV_FRONTEND }}
        ZIP_PASSWORD: ${{ secrets.FONTS_ZIP_PASSWORD }}
      run: |
        echo "$ENV_FRONTEND" > ./.env
        unzip -qq -P "$ZIP_PASSWORD"  ./../../.github/fonts.zip -d ./src/app/styles
        npm ci
        npm run build

    - name: Process admin
      working-directory: ./packages/admin
      env:
        ENV_ADMIN: ${{ secrets.ENV_ADMIN }}
      run: |
        echo "$ENV_ADMIN" > ./.env
        npm ci
