name: Check pull request's code quality

on:
  push:
    branches:
      - '**'
      - '!master'
      - '!develop'

jobs:
  lint:
    environment: code-quality
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Node.JS
      uses: actions/setup-node@v3
      with:
        node-version: 16.0.0

    - name: Install dependencies
      run: npm ci

    - name: Lint
      run: npm run -ws precommit

  build:
    environment: code-quality
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: montudor/action-zip@v1

    - name: Install Node.JS
      uses: actions/setup-node@v3
      with:
        node-version: 16.0.0

    - name: Install dependencies
      run: npm ci

    - name: Process backend
      working-directory: ./packages/backend
      env:
        ENV_BACKEND: ${{ secrets.ENV_BACKEND }}
      run: |
        npm ci
        npm run build

    - name: Process frontend
      working-directory: ./packages/frontend
      env:
        ENV_FRONTEND: ${{ secrets.ENV_FRONTEND }}
        ZIP_PASSWORD: ${{ secrets.FONTS_ZIP_PASSWORD }}
      run: |
        npm ci
        echo "$ENV_FRONTEND" >> ./.env.local
        unzip -qq -P "$ZIP_PASSWORD"  ./../../.github/fonts.zip -d ./src/app/styles
        npm run build

    - name: Process admin
      working-directory: ./packages/admin
      env:
        ENV_ADMIN: ${{ secrets.ENV_ADMIN }}
      run: |
        npm install
        echo "$ENV_ADMIN" >> ./.env
        npm run build
